### PR TITLE
doc/jedi-vim.txt: fix apostrophe

### PR DESCRIPTION
**Pull request by maxim-belkin**
’ character is not rendered nicely when LANG is not set.

### CODE REVIEW

**Comment by davidhalter** [comment]
Thanks for the patch!

I'm ok with this. Please merge @blueyed if you think so too.

**Comment by blueyed** [comment]
Thanks!

**Comment by maxim-belkin** [comment]
Thank you, Daniel!
Thank you, Dave!
🎉

**Comment by blueyed** [comment]
@maxim-belkin 
No, thank you! :) :heart:

**Pull request merged**
