### PR TITLE
Fix wildignore issues with tag stack

### PR DESCRIPTION
**Pull request by wilywampa**
Fix and add test cases for the problems described in https://github.com/davidhalter/jedi-vim/issues/482.

### CODE REVIEW

**Comment by davidhalter** [comment]
Could you document in the code why wildignore needs to be ignored?

**Comment by wilywampa** [comment]
@davidhalter 
Do maintainers get messaged automatically when a new commit is added to a pull request?

**Comment by blueyed** [comment]
@wilywampa 
> Do maintainers get messaged automatically when a new commit is added to a pull request?

Nope.

Thanks for the PR, looks fine to me! (untested)

**Comment by blueyed** [comment]
Committed (squashed) in 4b32847.

Thanks a lot for resolving this, @wilywampa - and especially for the test! :)

**Pull request closed without merging**
