### PR TITLE
test/signatures.vim: remove trailing spaces

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Working on https://github.com/davidhalter/jedi-vim/pull/652 to fix the tests for it.

**Comment by davidhalter** [comment]
This is fine. I'm not a big fan of it, but I also don't mind the change.

**Comment by blueyed** [comment]
We still have to find a fan of the current test setup.. :D

**Comment by davidhalter** [comment]
:D

**Pull request merged**
