### PR TITLE
tests: cover jedi_debug_info

### PR DESCRIPTION
**Pull request by blueyed**
TODO:

- [x] after https://github.com/davidhalter/jedi-vim/pull/991

### CODE REVIEW

**Comment by blueyed** [comment]
51% at least.. ;)

Fails on py27 due to:

> Error when running display_debug_info: Vim(return):Exception TypeError: '__call__() takes exactly 1 argument (2 given)' in <jedi._compatibility.finalize object at 0x7f0f8b98e360> ignored

IIRC this might be fixed with the update (#991).

**Comment by davidhalter** [comment]
BTW: The question is also how long we are going to support Python 2. I have deprecated it in Jedi and I will remove it after a while. I guess most VIM versions (including my old one) come with Python 3 support. Jedi can still deal with Python 2 (for a while), so people could just use `:let jedi#force_py_version=2.7` for the time being.

**Comment by blueyed** [comment]
@davidhalter IMHO it makes sense to remove it gets into the way, i.e. when we want to add type annotations etc, but then this would be easier after also dropping py35 - so no rush.

**Comment by blueyed** [comment]
> codecov/project — 51.54% (+3.71%) compared to 18b1a51

**Pull request merged**
