### PR TITLE
[WIP] Improve Python setup/loading

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
I think we should change the default from "auto" to "detect" (which just prefers py3).
See https://github.com/davidhalter/jedi-vim/pull/697/files#diff-6db9079804106af1d924941ee58e5cd4R480.

Any feedback, before I push the code changes for this?
/cc @purpleP @chenhouwu

**Comment by davidhalter** [comment]
I have no strong opinions on this. Let me know once you're ready to merge and I'll check if everything makes sense.

**Comment by blueyed** [comment]
Tried to rebase this just now - having an unpushed rebase locally already, but there are many conflicts and empty commits by now.  Likely should be closed, or some small improvements getting picked out of it.

**Comment by davidhalter** [comment]
I'm closing, because this makes improvements mostly to the Python 2/3 usage, whereas now we only use Python 3. So it's much simpler and this change is probably not needed.

**Pull request closed without merging**
