### PR TITLE
jedi#debug_info: escape script path for "git"

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/davidhalter/jedi-vim/issues/949

### CODE REVIEW

**Comment by blueyed** [comment]
@newuserha can you confirm that it works?

**Comment by NewUserHa** [comment]
no
```
 - jedi-vim git version: fatal: cannot change to 'C:\Program\ Files\Vim\vimfiles\plugged\jedi-vim': No such file or directory
 - jedi git submodule status: fatal: cannot change to 'C:\Program\ Files\Vim\vimfiles\plugged\jedi-vim': No such file or directory
 - parso git submodule status: fatal: cannot change to 'C:\Program\ Files\Vim\vimfiles\plugged\jedi-vim': No such file or directory
```

**Comment by blueyed** [comment]
Oh.. and now?

**Comment by NewUserHa** [comment]
```
You should run this in a buffer with filetype "python".
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: 89c995e-dirty
 - jedi git submodule status:  005f69390c4b1a3b864e7373cfcbdaf95e65411d pythonx/jedi (v0.15.1)
 - parso git submodule status:  c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso (v0.5.1)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `C:\Program Files\Vim\vim81\gvim.exe`
 - global sys.version: `3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]`
 - global site module: `C:\Program Files\Python37\Lib\site.py`
 
```
seems works now.
tested on `win10`.

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
