### PR TITLE
Logo files upload & Readme update

### PR DESCRIPTION
**Pull request by Tobaloidee**
Thanks for accepting and using my design Sir! Beast regards! - Tobaloidee

### CODE REVIEW

**Comment by davidhalter** [comment]
Awesome, thanks! Did you have a license in mind for the logo or are you just gifting it to me?

**Comment by Tobaloidee** [comment]
it's 
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons License</a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

Sir if it's okay and won't cause any conflict, but it is yours.. thanks so much!

**Comment by davidhalter** [comment]
Fair enough. Thank you!

**Comment by davidhalter** [comment]
Damn. Wanted to squash. Whatever.

**Comment by Tobaloidee** [comment]
what do you mean Sir?

**Comment by davidhalter** [comment]
I wanted to squash-commit your changes. This means that there will only be one commit in the git history. Now there are four. But it's really all my problem.

**Comment by blueyed** [comment]
Why does this also contain `logo/logotype-b.svg` and `logo/logotype-b.png`? (https://github.com/Tobaloidee/jedi-vim/blob/d853ff5344665059e0cb873f1e01d842eaf0778b/logo/logotype-b.png)

I guess those could be removed?
Also the favicons then probably.

Also, isn't `.svg` enough nowadays?

(my point is that the repo should not contain unnecessary files, especially when they are rather big - we have ~100kb for the logo(s) now additionally)

**Comment by blueyed** [comment]
(also having them now all in the history is rather unfortunate, since it makes all those git checkouts there bigger - assuming they are not shallow copies, which is luckily the case for a lot of plugin managers)

**Comment by Tobaloidee** [comment]
I thought its okay uploading all the versions in svg and png. I apologize Sirs..I am not aware of the limitations..thank you..

**Comment by davidhalter** [comment]
I mean, we can still force push? I think it's fine. Feel free if you want @blueyed, but please do it in the next couple of days.

**Comment by blueyed** [comment]
> force-push

Oh.. well..
https://github.com/davidhalter/jedi-vim/pull/837

**Pull request merged**
