### PR TITLE
update jedi to v0.19.2 and parso to v0.8.4

### PR DESCRIPTION
**Pull request by jgb**

### CODE REVIEW

**Comment by davidhalter** [comment]
Thanks. Unfortunately somebody needs to look at the tests CI. Somethin g seems wrong, but it might as well be test. I would have to investigate.

BTW: Ignore the coverage CI, it should probably just be removed, it has been defunctional for a long time.

**Comment by jgb** [comment]
> Thanks. Unfortunately somebody needs to look at the tests CI. Somethin g seems wrong, but it might as well be test. I would have to investigate.
> 
> BTW: Ignore the coverage CI, it should probably just be removed, it has been defunctional for a long time.

I'm running the tests locally, it seems it's the jedi upgrade that causes the tests to fail, upgrading parso alone doesn't cause any harm.
I'll try to see if it's a real problem or just an adjustment of the test is needed.

**Comment by davidhalter** [comment]
I'll check. Thanks for looking!

The tests are sometimes a bit brittle here and react to non-problems, so don't worry.

**Comment by davidhalter** [comment]
I fixed a few things around CI and basically just removed test parts that did not make sense: https://github.com/davidhalter/jedi-vim/pull/1131

Thanks for your PR again.

**Pull request merged**
