### PR TITLE
Add JediClearCache command

### PR DESCRIPTION
**Pull request by blueyed**
This can be used to work around issues like
https://github.com/davidhalter/jedi/issues/784.

Not sure about the interface and/or the methods it calls - to be discussed.

### CODE REVIEW

**Comment by davidhalter** [comment]
Should I already merge this one (since Jedi is not fixed)?

**Comment by blueyed** [comment]
Yes.
Should it be documented?

**Comment by davidhalter** [comment]
I think we should not document it, yet. There's a chance that it's not necessary anymore with the new parser. Ok? It's also not part of the Jedi API.

**Comment by blueyed** [comment]
Makes sense.

The API being used here is OK though?
Couldn't it become official for Jedi? (apart from this issue)

**Comment by davidhalter** [comment]
> Couldn't it become official for Jedi?

That really depends. IMO the user doesn't want to deal with caches. They should not get corrupted in the first place - so this feels more like a workaround. I know that doesn't really sound good at the moment, but I'm really commited to fixing the existing flaws (having spent a lot of time actually removing problem parts in the last few months).

**Pull request merged**
