### PR TITLE
Fix "goto" with multiple results

### PR DESCRIPTION
**Pull request by blueyed**
E.g. with `os.path`.

### CODE REVIEW

**Comment by davidhalter** [comment]
I'll try to test it locally.

**Comment by blueyed** [comment]
> I'll try to test it locally.

:+1:
Works on `os.path`, where it should give you two results to choose from.

**Comment by davidhalter** [comment]
It seems like goto is working again like I assumed.

The only thing I'm not happy about now is the `cc` for usages (which was in there before :)). I feel like this makes it harder to actually go to something (and most people like me don't know about `:ccl`, which is also pretty annoying to type). My workflow is usually that I use usages and then just go to one of them. Feel free to comment, maybe your workflow is better and I just don't know how to deal with it.

But: This can be merged, since it just improves the situation.

**Comment by davidhalter** [comment]
BTW: My issue might just be the focus of the window. IMO selecting the current usage makes sense, but leaving the window doesn't.

What do you think?

**Comment by blueyed** [comment]
> BTW: My issue might just be the focus of the window. IMO selecting the current usage makes sense, but leaving the quickfix window doesn't.
> 
> What do you think?

I can see what you mean.
My use is just seeing where it is used, but it makes sense to select it explicitly.  Will look into it later.

**Comment by blueyed** [comment]
@davidhalter pushed a fixup.

**Comment by davidhalter** [comment]
Makes sense, I guess. Thanks!

**Pull request merged**
