### PR TITLE
Update jedi submodule to current master

### PR DESCRIPTION
**Pull request by blueyed**
Comparison: https://github.com/davidhalter/jedi/compare/995a6531225ba0b65e1ff863d97e5404d989047b...2ba78ab725f1e02dfef8bc50b0204cf656e8ee23.

Just suggesting it - feel free to reject it.

I thought it would be good to get some of the fixes into jedi-vim officially.

### CODE REVIEW

**Comment by davidhalter** [comment]
I'm ok with this. However I'd probably feel more inclined to merge Jedi's dev into master first.

**Comment by blueyed** [comment]
> However I'd probably feel more inclined to merge Jedi's dev into master first.

Ok! :+1: 

I'm waiting here.. ;)

**Comment by davidhalter** [comment]
I realized that master is actually further than I thought. I'm merging.

I'm still not 100% sure this is the right thing to do. However now people at least have a shot at trying a more stable version. This is something that I have taken from a lot of people by not releasing in summer. Well anyway, next release is going to be good and consider this a temporary solution ;)

**Comment by blueyed** [comment]
Unfortunately it seems to break the tests?!
https://travis-ci.org/davidhalter/jedi-vim/builds/176439900 (restarted it now to be sure it's not something random)

**Pull request merged**
