### PR TITLE
Replace deprecated checkhealth syntax with newer syntax

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by davidhalter** [comment]
Can we do this without lua? My current VIM for example doesn't have lua support.

**Comment by dundargoc** [comment]
`:checkhealth` doesn't even work on vim since it's a neovim-exclusive command, and neovim always ships with lua.

**Comment by davidhalter** [comment]
Sorry, this is not code I have written. I'm trying my best to understand.

So do I understand this correctly: This whole function is only about nvim and will never be invoked by VIM? I don't understand the mechanism.

**Comment by dundargoc** [comment]
> This whole function is only about nvim and will never be invoked by VIM?

Yeah. Try running `:checkhealth jedi` in vim. Nothing will happen. This is a neovim-only functionality so it should be fine to use lua functionality through vimscript as lua is shipped with neovim.

**Comment by davidhalter** [comment]
Thanks!

**Pull request merged**
