### PR TITLE
Upgrade jedi to 0.12.1, forgot to upgrade it when upgrading parso

### LINKED ISSUE #845: Auto complete not working
### Issue
Auto complete stopped working, returning the message 

`Omni completion (^O^N^P) Pattern not found`

#### Jedi-vim debug information
Using Python version: 3
 - global sys.version: `3.6.5 (default, Apr  1 2018, 05:46:30), [GCC 7.3.0]`
 - global site module: `/usr/lib/python3.6/site.py`
Jedi path: `/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.0
 - environment: `<Environment: 3.6.5 in /home/mwesthelle/projects/chatbot/venv>`
 - sys_path:
    - `/usr/lib/python36.zip`
    - `/usr/lib/python3.6`
    - `/usr/lib/python3.6/lib-dynload`
    - `/home/mwesthelle/projects/chatbot/venv/lib/python3.6/site-packages`
 - jedi-vim git version: 0.9.0-29-g7cade1f
 - jedi git submodule status:  bd7c65d9639c2d451d44c6d135b4f6043a918950 pythonx/jedi (v0.12.0)
 - parso git submodule status:  e6bc924fbabbfa3090044e475c91a7655b9c6e9b pythonx/parso (v0.3.1)

##### Settings
```
  omnifunc=jedi#completions
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim
  completeopt=menuone,longest,preview
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim
```

#### :version
```

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +cryptv            -footer            +mksession         +path_extra        +syntax            +viminfo
+arabic            +cscope            +fork()            +modify_fname      +perl              +tag_binary        +vreplace
+autocmd           +cursorbind        +gettext           +mouse             +persistent_undo   +tag_old_static    +wildignore
-autoservername    +cursorshape       -hangul_input      +mouseshape        +postscript        -tag_any_white     +wildmenu
+balloon_eval      +dialog_con_gui    +iconv             +mouse_dec         +printer           +tcl               +windows
+balloon_eval_term +diff              +insert_expand     +mouse_gpm         +profile           +termguicolors     +writebackup
+browse            +digraphs          +job               -mouse_jsbterm     -python            +terminal          +X11
++builtin_terms    +dnd               +jumplist          +mouse_netterm     +python3           +terminfo          -xfontset
+byte_offset       -ebcdic            +keymap            +mouse_sgr         +quickfix          +termresponse      +xim
+channel           +emacs_tags        +lambda            -mouse_sysmouse    +reltime           +textobjects       +xpm
+cindent           +eval              +langmap           +mouse_urxvt       +rightleft         +timers            +xsmp_interact
+clientserver      +ex_extra          +libcall           +mouse_xterm       -ruby              +title             +xterm_clipboard
+clipboard         +extra_search      +linebreak         +multi_byte        +scrollbind        +toolbar           -xterm_save
+cmdline_compl     +farsi             +lispindent        +multi_lang        +signs             +user_commands     
+cmdline_hist      +file_in_path      +listcmds          -mzscheme          +smartindent       +vertsplit         
+cmdline_info      +find_in_path      +localmap          +netbeans_intg     +startuptime       +virtualedit       
+comments          +float             +lua               +num64             +statusline        +visual            
+conceal           +folding           +menu              +packages          -sun_workshop      +visualextra       
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-NQEcoP/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm     
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>

Traceback (most recent call last):
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 128, in get_stack_at_position
    p.parse(tokens=tokenize_without_endmarker(code))
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/python/parser.py", line 82, in parse
    return super(Parser, self).parse(tokens)
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 127, in parse
    for token in tokens:
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/python/parser.py", line 198, in _recovery_tokenize
    for token in tokens:
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 111, in tokenize_without_endmarker
    raise EndMarkerReached()
jedi.api.helpers.get_stack_at_position.<locals>.EndMarkerReached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 246, in completions
    completions = script.completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 97, in completions
    completion_names = self._get_context_completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 125, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 130, in get_stack_at_position
    return Stack(p.pgen_parser.stack)
AttributeError: 'Parser' object has no attribute 'pgen_parser'

Traceback (most recent call last):
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 128, in get_stack_at_position
    p.parse(tokens=tokenize_without_endmarker(code))
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/python/parser.py", line 82, in parse
    return super(Parser, self).parse(tokens)
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 127, in parse
    for token in tokens:
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/python/parser.py", line 198, in _recovery_tokenize
    for token in tokens:
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 111, in tokenize_without_endmarker
    raise EndMarkerReached()
jedi.api.helpers.get_stack_at_position.<locals>.EndMarkerReached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 246, in completions
    completions = script.completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 97, in completions
    completion_names = self._get_context_completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 125, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 130, in get_stack_at_position
    return Stack(p.pgen_parser.stack)
AttributeError: 'Parser' object has no attribute 'pgen_parser'


Traceback (most recent call last):
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 128, in get_stack_at_position
    p.parse(tokens=tokenize_without_endmarker(code))
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/python/parser.py", line 82, in parse
    return super(Parser, self).parse(tokens)
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 127, in parse
    for token in tokens:
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/python/parser.py", line 198, in _recovery_tokenize
    for token in tokens:
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 111, in tokenize_without_endmarker
    raise EndMarkerReached()
jedi.api.helpers.get_stack_at_position.<locals>.EndMarkerReached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 246, in completions
    completions = script.completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 97, in completions
    completion_names = self._get_context_completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 125, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 130, in get_stack_at_position
    return Stack(p.pgen_parser.stack)
AttributeError: 'Parser' object has no attribute 'pgen_parser'


Traceback (most recent call last):
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 128, in get_stack_at_position
    p.parse(tokens=tokenize_without_endmarker(code))
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/python/parser.py", line 82, in parse
    return super(Parser, self).parse(tokens)
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 127, in parse
    for token in tokens:
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/parso/parso/python/parser.py", line 198, in _recovery_tokenize
    for token in tokens:
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 111, in tokenize_without_endmarker
    raise EndMarkerReached()
jedi.api.helpers.get_stack_at_position.<locals>.EndMarkerReached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 246, in completions
    completions = script.completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 97, in completions
    completion_names = self._get_context_completions()
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 125, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "/home/mwesthelle/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 130, in get_stack_at_position
    return Stack(p.pgen_parser.stack)
AttributeError: 'Parser' object has no attribute 'pgen_parser'





```

<details><summary>:scriptnames</summary>

```
  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim80/debian.vim
  3: /usr/share/vim/vim80/syntax/syntax.vim
  4: /usr/share/vim/vim80/syntax/synload.vim
  5: /usr/share/vim/vim80/syntax/syncolor.vim
  6: /usr/share/vim/vim80/filetype.vim
  7: ~/.vimrc
  8: /usr/share/vim/vim80/ftoff.vim
  9: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
 10: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 11: ~/.vim/bundle/vim-fugitive/ftdetect/fugitive.vim
 12: /usr/share/vim/vim80/ftplugin.vim
 13: /usr/share/vim/vim80/indent.vim
 14: ~/.vim/bundle/vim-moonfly-colors/colors/moonfly.vim
 15: /usr/share/vim/vim80/syntax/nosyntax.vim
 16: ~/.vim/bundle/auto-pairs/plugin/auto-pairs.vim
 17: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 18: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 19: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 20: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 21: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 22: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 23: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 24: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 25: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 26: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 27: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 28: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 29: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 30: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 31: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 32: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 33: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 34: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 35: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 36: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 37: ~/.vim/bundle/quick-scope/plugin/quick_scope.vim
 38: ~/.vim/bundle/supertab/plugin/supertab.vim
 39: ~/.vim/bundle/syntastic/plugin/syntastic/autoloclist.vim
 40: ~/.vim/bundle/syntastic/plugin/syntastic/balloons.vim
 41: ~/.vim/bundle/syntastic/plugin/syntastic/checker.vim
 42: ~/.vim/bundle/syntastic/plugin/syntastic/cursor.vim
 43: ~/.vim/bundle/syntastic/plugin/syntastic/highlighting.vim
 44: ~/.vim/bundle/syntastic/plugin/syntastic/loclist.vim
 45: ~/.vim/bundle/syntastic/plugin/syntastic/modemap.vim
 46: ~/.vim/bundle/syntastic/plugin/syntastic/notifiers.vim
 47: ~/.vim/bundle/syntastic/plugin/syntastic/registry.vim
 48: ~/.vim/bundle/syntastic/plugin/syntastic/signs.vim
 49: ~/.vim/bundle/syntastic/plugin/syntastic.vim
 50: ~/.vim/bundle/syntastic/autoload/syntastic/util.vim
 51: ~/.vim/bundle/tagbar/plugin/tagbar.vim
 52: ~/.vim/bundle/vim-airline/plugin/airline.vim
 53: ~/.vim/bundle/vim-airline/autoload/airline/init.vim
 54: ~/.vim/bundle/vim-airline/autoload/airline/parts.vim
 55: ~/.vim/bundle/vim-airline-themes/plugin/airline-themes.vim
 56: ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
 57: ~/.vim/bundle/vim-gutentags/plugin/gutentags.vim
 58: ~/.vim/bundle/vimify/plugin/vimify.vim
 59: ~/.vim/bundle/vim-licenses/plugin/licenses.vim
 60: ~/.vim/bundle/vim-surround/plugin/surround.vim
 61: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
 62: /usr/share/vim/vim80/plugin/gzip.vim
 63: /usr/share/vim/vim80/plugin/logiPat.vim
 64: /usr/share/vim/vim80/plugin/manpager.vim
 65: /usr/share/vim/vim80/plugin/matchparen.vim
 66: /usr/share/vim/vim80/plugin/netrwPlugin.vim
 67: /usr/share/vim/vim80/plugin/rrhelper.vim
 68: /usr/share/vim/vim80/plugin/spellfile.vim
 69: /usr/share/vim/vim80/plugin/tarPlugin.vim
 70: /usr/share/vim/vim80/plugin/tohtml.vim
 71: /usr/share/vim/vim80/plugin/vimballPlugin.vim
 72: /usr/share/vim/vim80/plugin/zipPlugin.vim
 73: ~/.vim/bundle/indentLine/after/plugin/indentLine.vim
 74: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 75: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 76: /usr/share/vim/vim80/ftplugin/python.vim
 77: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 78: /usr/share/vim/vim80/indent/python.vim
 79: /usr/share/vim/vim80/syntax/python.vim
 80: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 81: ~/.vim/bundle/vim-airline/autoload/airline/extensions.vim
 82: ~/.vim/bundle/vim-airline/autoload/airline/extensions/quickfix.vim
 83: ~/.vim/bundle/vim-airline/autoload/airline.vim
 84: ~/.vim/bundle/vim-airline/autoload/airline/extensions/netrw.vim
 85: ~/.vim/bundle/vim-airline/autoload/airline/extensions/term.vim
 86: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tagbar.vim
 87: ~/.vim/bundle/vim-airline/autoload/airline/util.vim
 88: ~/.vim/bundle/vim-airline/autoload/airline/extensions/branch.vim
 89: ~/.vim/bundle/vim-airline/autoload/airline/extensions/fugitiveline.vim
 90: ~/.vim/bundle/vim-airline/autoload/airline/extensions/virtualenv.vim
 91: ~/.vim/bundle/vim-airline/autoload/airline/extensions/syntastic.vim
 92: ~/.vim/bundle/vim-airline/autoload/airline/extensions/whitespace.vim
 93: ~/.vim/bundle/vim-airline/autoload/airline/extensions/po.vim
 94: ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
 95: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline.vim
 96: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/autoshow.vim
 97: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/tabs.vim
 98: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buffers.vim
 99: ~/.vim/bundle/vim-airline/autoload/airline/extensions/gutentags.vim
100: ~/.vim/bundle/vim-airline/autoload/airline/extensions/keymap.vim
101: ~/.vim/bundle/vimtex/autoload/vimtex.vim
102: ~/.vim/bundle/vim-airline/autoload/airline/extensions/vimtex.vim
103: ~/.vim/bundle/vim-airline/autoload/airline/section.vim
104: ~/.vim/bundle/vim-airline/autoload/airline/highlighter.vim
105: ~/.vim/bundle/vim-airline-themes/autoload/airline/themes/deus.vim
106: ~/.vim/bundle/vim-airline/autoload/airline/themes.vim
107: ~/.vim/bundle/vim-airline/autoload/airline/builder.vim
108: ~/.vim/bundle/vim-airline/autoload/airline/extensions/default.vim
109: ~/.vim/bundle/vim-gutentags/autoload/gutentags.vim
110: ~/.vim/bundle/syntastic/autoload/syntastic/log.vim
111: ~/.vim/bundle/quick-scope/autoload/quick_scope.vim
112: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/ctrlspace.vim
113: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/builder.vim
114: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buflist.vim
115: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/formatters/default.vim
116: ~/.vim/bundle/vim-airline/autoload/airline/async.vim
117: ~/.vim/bundle/vim-fugitive/autoload/fugitive.vim
118: ~/.vim/bundle/tagbar/autoload/tagbar.vim
119: ~/.vim/bundle/tagbar/autoload/tagbar/debug.vim
120: ~/.vim/bundle/tagbar/autoload/tagbar/types/uctags.vim
121: ~/.vim/bundle/tagbar/autoload/tagbar/prototypes/typeinfo.vim
122: ~/.vim/bundle/tagbar/autoload/tagbar/state.vim
123: /usr/share/vim/vim80/ftplugin/vim.vim
124: /usr/share/vim/vim80/indent/vim.vim
125: /usr/share/vim/vim80/syntax/vim.vim
126: /usr/share/vim/vim80/syntax/lua.vim
127: /usr/share/vim/vim80/syntax/perl.vim
128: /usr/share/vim/vim80/syntax/pod.vim
```
</details>

### PR DESCRIPTION
**Pull request by davidhalter**
Fixes #845.

### CODE REVIEW

**Comment by davidhalter** [comment]
I tried to reenable the tests. No idea anymore why they were disabled (they are passing at the moment).

**Comment by davidhalter** [comment]
Damn. I force pushed the wrong branch. Let me clean it up...

**Comment by davidhalter** [comment]
@blueyed I hope I didn't mess anything up. I feel like all the commits are still there and I didn't even mess up the history. Sorry for the inconvenience. 

I didn't want to merge, but since the thing got pushed and a lot of people depend on it (#845) and jedi-vim was fully broken, I feel like it's good that we fixed it instantly.

**Comment by blueyed** [comment]
Sure, thanks for handling it!

Should have checked it myself (IIRC the parso update was from me) - but I tend to use master branches everywhere.. :/

But commits are missing in master, i.e. 7e1d96f and the others from this PR.

**Comment by blueyed** [comment]
But it seems 2bb7677 is meant to replace them, right?

**Comment by davidhalter** [comment]
Yes, the commits in here don't matter, I meant to force push this one. Everything should just be fine.

**Pull request merged**
