### PR TITLE
Escape shell args properly on Windows

### PR DESCRIPTION
**Pull request by BohrShaw**
`cmd.exe` would strip off the first and last quote on a command.

### CODE REVIEW

**Comment by poppyschmo** [comment]
This fix worked for me on Windows with all `'shell'`-related options left at default (`'shellslash'`, `'shellxquote'`, etc.). Worked on posix/*sh too. Thanks.

**Comment by blueyed** [comment]
See also https://github.com/davidhalter/jedi-vim/pull/441/files, which I prefer, since there's no `shellescape` required here.

Thanks for confirming the issue though!

**Comment by blueyed** [comment]
Sorry, I've just noticed that using `shellescape()` would have been cleaner and more robust probably in general.

Please let me know in case some special `'shell'`-related option now causes issues with the change after 95b8dd7.

**Comment by poppyschmo** [comment]
Tried a limited use-case scenario (MinGW), just to test, with `'shellslash'` on, `'shellxquote'` set to `"`, and `set shell=c:/\"Program\ Files\"/Git/usr/bin/bash.exe\ --login\ -i`. Worked before latest push. Also works using `shellescape()`.

**Comment by blueyed** [comment]
@poppyschmo 
Thanks.

> Worked before latest push

The question however was rather if it still work, so _after_ the latest push..

**Comment by poppyschmo** [comment]
Sorry, should have been clearer. No, the MinGW test case doesn't work after the latest push. Doubt many Windows users will be affected, though, since most use the default `%COMSPEC%`. Thanks.

**Comment by blueyed** [comment]
I see.
Sorry for the mess and thanks for investigating.
Fixed in dc96886 now.

**Pull request closed without merging**
