### PR TITLE
Update parso/jedi (v0.6.0, v0.16.0+)

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by davidhalter** [comment]
I don't really understand the error message in the CI. Did this exist before? Tests are just passing with the coverage build. Happy to merge already, but I feel like you can decide better if we want to wait with a merge or not.

**Comment by blueyed** [comment]
```
============================= test session starts ==============================
platform linux -- Python 3.7.1, pytest-4.3.1, py-1.7.0, pluggy-0.8.0
rootdir: /home/travis/build/davidhalter/jedi-vim, inifile: setup.cfg
plugins: cov-2.8.1
collected 6 items                                                              
test/test_integration.py ..F...                                          [100%]
=================================== FAILURES ===================================
_________________ test_integration[test/vspec/completions.vim] _________________
test/vspec/completions.vim failed:
not found in 'runtimepath': "ftdetect/*.vim"
ok 1 - completions longest in completeopt
ok 2 - completions no smart import by default=jedi#complete_opened(0)
=jedi#complete_opened(0)
ok 3 - completions import=jedi#complete_opened(0)
=jedi#complete_opened(0)
ok 4 - completions exception=jedi#complete_opened(0)
=jedi#complete_opened(0)
ok 5 - completions multi complete=jedi#complete_opened(0)
ok 6 - completions cycling through entries popup_select_first=0=jedi#complete_opened(0)
ok 7 - completions cycling through entries popup_select_first=1=jedi#complete_opened(0)
=jedi#complete_opened(0)
=jedi#complete_opened(0)
ok 8 - completions cycling through entries popup_select_first=1 and longest
not ok 9 - smart completions smart import
# function jedi#clear_call_signatures[6]..provider#python3#Call, line 18
# Vim(return):Invalid channel: 3
not ok 10 - smart completions no smart import after space
# function jedi#clear_call_signatures[6]..provider#python3#Call, line 18
# Vim(return):Invalid channel: 3
1..10
```

I'll have to investigate.  I think it is good to have green CI, and it worked with https://github.com/davidhalter/jedi-vim/pull/990.

**Comment by davidhalter** [comment]
There might be deprecation warnings maybe? That's the only thing that comes to my mind that might cause this.

**Comment by blueyed** [comment]
This commit appears to trigger it: https://github.com/davidhalter/jedi/commit/e3e6727a2d1b037d73f25462b9b080afad24b25a
Filed https://github.com/davidhalter/jedi/issues/1490.

When triggering it manually I see the above error, but completions show up - I guess it is crashing Neovim due to too many messages on stderr or similar.  (it appears to also require pytest-cov to trigger the crash - "coverage -m" appears to be fine)

**Comment by blueyed** [comment]
Yeah, it gets triggered via the preview window - `:set completeopt-=preview` makes it not show up.

**Comment by blueyed** [comment]
Updated to use Jedi master (ref https://github.com/davidhalter/jedi/issues/1490#issuecomment-581193273).

**Comment by blueyed** [comment]
\o/
Thanks @davidhalter ! :)

**Comment by davidhalter** [comment]
Thanks for doing the work here :)

I'm finally on my way to < 10 open Jedi issues :)

**Comment by blueyed** [comment]
It's my pleasure helping you.. :)
Thanks for Jedi in the first place - it's really nice with all the new features with regard to typing stubs!

**Pull request merged**
