### PR TITLE
Update parso and Jedi

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by davidhalter** [comment]
The signature change is definitely ok. The additional ANY probably comes from a typeshed upgrade.

**Comment by blueyed** [comment]
So both/all test should be updated?

**Comment by davidhalter** [comment]
Yeah, you can probably apply this:

```
diff --git a/test/vspec/signatures.vim b/test/vspec/signatures.vim
index ca4248e..6090ee9 100644
--- a/test/vspec/signatures.vim
+++ b/test/vspec/signatures.vim
@@ -41,7 +41,7 @@ describe 'signatures'
         doautocmd CursorHoldI
         noautocmd normal istaticmethod()
         doautocmd CursorHoldI
-        Expect getline(1) == '?!?jedi=0, ?!?            (*_*f: Callable*_*) ?!?jedi?!?'
+        Expect getline(1) == '?!?jedi=0, ?!?            (*_*f: Callable[..., Any]*_*) ?!?jedi?!?'
     end
 
     it 'no signature'
@@ -68,7 +68,7 @@ describe 'signatures'
         redir => msg
         Python jedi_vim.show_call_signatures()
         redir END
-        Expect msg == "\nstaticmethod(f: Callable)"
+        Expect msg == "\nstaticmethod(f: Callable[..., Any])"
 
         redir => msg
         doautocmd InsertLeave
```

It's IMO correct and would solve the issue.

**Comment by blueyed** [comment]
Hmm, it appears to be related to the Python version being used?!
"make test" passes locally without your patch, but fails with it (Python 3.8.0)

**Comment by davidhalter** [comment]
For me all of  `python2.7 -m pytest`, `python3.5 -m pytest` and `python3.8 -m pytest` are passing (locally).

What fails for you in 3.8? Could you give me your log?

**Comment by blueyed** [comment]
```console
% COLUMNS=80 python -m pytest                                                                                                                             🐍? (jedi-vim@3.8.0)
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
rootdir: /home/daniel/.dotfiles/vim/plugged/jedi-vim, inifile: setup.cfg, testpaths: test
collected 7 items

test/test_integration.py .....F.                                         [100%]

=================================== FAILURES ===================================
_________________ test_integration[test/vspec/signatures.vim] __________________
test/vspec/signatures.vim failed:
ok 1 - signatures simple
4 buffers wiped out
--- Autocommands ---
jedi_call_signatures  CursorHoldI
<buffer=6>
call jedi#show_call_signatures()
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 630
jedi_call_signatures  InsertEnter
<buffer=6>
let s:show_call_signatures_last = [0, 0, '']
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 621
let b:_jedi_orig_updatetime = &updatetime | let &updatetime = g:jedi#show_call_signatures_delay
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 624
jedi_call_signatures  InsertLeave
<buffer=6>
call jedi#clear_call_signatures()
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 622
if exists('b:_jedi_orig_updatetime') |   let &updatetime = b:_jedi_orig_updatetime |   unlet b:_jedi_orig_updatetime | endif
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 626
--- Autocommands ---
jedi_call_signatures  CursorHoldI
<buffer=5>
call jedi#show_call_signatures()
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 630
jedi_call_signatures  InsertEnter
<buffer=5>
let s:show_call_signatures_last = [0, 0, '']
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 621
let b:_jedi_orig_updatetime = &updatetime | let &updatetime = g:jedi#show_call_signatures_delay
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 624
jedi_call_signatures  InsertLeave
<buffer=5>
call jedi#clear_call_signatures()
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 622
if exists('b:_jedi_orig_updatetime') |   let &updatetime = b:_jedi_orig_updatetime |   unlet b:_jedi_orig_updatetime | endif
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/autoload/jedi.vim line 626
ok 2 - signatures multiple buffers
2 buffers wiped out
not ok 3 - signatures simple after CursorHoldI with only parenthesis
# Expected getline(1) == '?!?jedi=0, ?!?            (*_*f: Callable[..., Any]*_*) ?!?jedi?!?' at line 5
#       Actual value: "?!?jedi=0, ?!?            (*_*f: Callable*_*) ?!?jedi?!?"
#     Expected value: "?!?jedi=0, ?!?            (*_*f: Callable[..., Any]*_*) ?!?jedi?!?"
ok 4 - signatures highlights correct argument
ok 5 - signatures no signature
ok 6 - signatures signatures disabled
staticmethod(f: Callable)
not ok 7 - signatures command line simple
# Expected msg == "\nstaticmethod(f: Callable[..., Any])" at line 8
#       Actual value: "\nstaticmethod(f: Callable)"
#     Expected value: "\nstaticmethod(f: Callable[..., Any])"
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(arg1, …)
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(…, arg2, …)
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(…, a, b, c)
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(…, c)
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(…)
ok 8 - signatures command line truncation
ok 9 - signatures command line no signature
1..9

========================= 1 failed, 6 passed in 4.42s ==========================
```
(with your patch)

**Comment by blueyed** [comment]
I think I had the typeshed submodue not synced, but it is still failing (slightly differently from a quick glance).  Will push your patch for now, needs more investigation probably.

**Comment by davidhalter** [comment]
Took me way longer than it should have taken to realize that I was not using latest master. The patch should be like this:

```
diff --git a/test/vspec/signatures.vim b/test/vspec/signatures.vim
index 22bfb73..933df1c 100644
--- a/test/vspec/signatures.vim
+++ b/test/vspec/signatures.vim
@@ -41,7 +41,7 @@ describe 'signatures'
         doautocmd CursorHoldI
         noautocmd normal istaticmethod()
         doautocmd CursorHoldI
-        Expect getline(1) == '?!?jedi=0, ?!?            (*_*f: Callable*_*) ?!?jedi?!?'
+        Expect getline(1) == '?!?jedi=0, ?!?            (*_*f: Callable[..., Any]*_*) ?!?jedi?!?'
     end
 
     it 'highlights correct argument'
@@ -54,14 +54,14 @@ describe 'signatures'
         " Move to "=" - hightlights "sep=...".
         noautocmd normal 5h
         doautocmd CursorHoldI
-        Expect getline(1) =~# '\V\^?!?jedi=0, ?!?     (*values: object, *_*sep: Text=...*_*'
+        Expect getline(1) =~# '\V\^?!?jedi=0, ?!?     (*values: object, *_*sep: Optional[Text]=...*_*'
         " Move left to "=" - hightlights first argument ("values").
         " NOTE: it is arguable that maybe "sep=..." should be highlighted
         "       still, but this tests for the cache to be "busted", and that
         "       fresh results are retrieved from Jedi.
         noautocmd normal h
         doautocmd CursorHoldI
-        Expect getline(1) =~# '\V\^?!?jedi=0, ?!?     (*_**values: object*_*, sep: Text=...,'
+        Expect getline(1) =~# '\V\^?!?jedi=0, ?!?     (*_**values: object*_*, sep: Optional[Text]=...,'
     end
 
     it 'no signature'
@@ -88,7 +88,7 @@ describe 'signatures'
         redir => msg
         Python jedi_vim.show_call_signatures()
         redir END
-        Expect msg == "\nstaticmethod(f: Callable)"
+        Expect msg == "\nstaticmethod(f: Callable[..., Any])"
 
         redir => msg
         doautocmd InsertLeave
```

**Pull request merged**
