### PR TITLE
Update Jedi to v0.15.0

### LINKED ISSUE #498: Why jedi-vim is too slow compared with ptpython
I know already there is a relevant issue #163 , but watch the gif at first.
ptpython

See? ptpython is blazingly fast the first time it completes numpy, which is considered a large module.
I think the reasons lie behind:
1. ptpython uses a global cache
2. VimL is slow compared with Python
3. ptpython completes at every stroke, making it fast with the next eval.

It doesn't matter for who write daily small scripts and for who edits all the time without leaving vim. How about for those who write small scientific computation scripts?
Any suggestions?

### LINKED ISSUE #779: Open file in new tab .
### Issue

Currently if the defination is not in opened file vim will open the file containing the defination in same tab. Can't there we anything like if the defination is not in current file open new file in new tab.

<!--
Include if relevant.

Please provide steps to reproduce it here, preferably based on a minimal Vim
configuration.

You can use the following template (save it as `minimal.vimrc` in the directory
where jedi-vim is installed, `cd` into that directory, and run Vim with
`vim -u minimal.vimrc`):

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

" Put your config changes here.
" let g:jedi#show_call_signatures=1

syntax on
filetype plugin indent on
```

Please provide the `minimal.vimrc` you have used here, too.
-->


<!--
Please execute `:redir @+> | silent verb JediDebugInfo | redir END` in a
Python buffer to copy debug information into your clipboard.
Then paste it here.
-->

### LINKED ISSUE #780: this plug not worked for third-party modules
### Issue

I,m a newer for vim, I want to write python3 code in vim, so I have install this plug with neovim in ubuntu systerm. The jedi already installed using pip3 tools. In most case, this tools works good for python code.

The problem is some third-party modules using many .so files, I guess these are some function realized by c or cpp code. and in this situation, the completion not worked. I have test the pygame and matplot mould, they both have the similar problem. 

I also try other autocompletion tools, such as nvim-completion-manager, YCM, jedi-vim, they all have the same problem. Other guys suggest me this is a jedi problem, so i post this problem here.

### Steps to reproduce

you can try this code:

import pygame
pygame.init()
screen = pygame.display.set_mode((640, 480), 0, 32)

The "set_mode" will not complete, and jedi-vim goto command also not work. The array fuction in numpy module have the same issue. I don't know how to solve this issue.

by the way, I also use the following code to check the jedi work or not, and not found something strange.
        import pygame
        print(pygame)

        import jedi
        list = jedi.Script('import pygame; pygame.display.').completions()
        print(list)

the output is:
       <module 'pygame' from '/usr/local/lib/python3.5/dist-packages/pygame/__init__.py'>

        [<Completion: info>, <Completion: name>, <Completion: reason>, <Completion: urgent>, <Completion: warn>, <Completion: _NOT_IMPLEMENTED_>, <Completion: __class__>, <Completion: __delattr__>, <Completion: __dir__>, <Completion: __doc__>, <Completion: __eq__>, <Completion: __format__>, <Completion: __ge__>, <Completion: __getattr__>, <Completion: __getattribute__>, <Completion: __gt__>, <Completion: __hash__>, <Completion: __init__>, <Completion: __le__>, <Completion: __lt__>, <Completion: __ne__>, <Completion: __new__>, <Completion: __nonzero__>, <Completion: __reduce__>, <Completion: __reduce_ex__>, <Completion: __repr__>, <Completion: __setattr__>, <Completion: __sizeof__>, <Completion: __str__>, <Completion: __subclasshook__>]

### Output of “:verbose JediDebugInfo”

:verbose JediDebugInfoe...
#### Jedi-vim debug information
Using Python version: 3
 - sys.version: `3.5.2 (default, Nov 23 2017, 16:37:01), [GCC 5.4.0 20160609]`
 - site module: `/usr/lib/python3.5/site.py`
Jedi path: `/home/jj/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init
__.py`
 - version: 0.11.1
 - sys_path:
    - `/usr/lib/python35.zip`
    - `/usr/lib/python3.5`
    - `/usr/lib/python3.5/plat-x86_64-linux-gnu`
    - `/usr/lib/python3.5/lib-dynload`
    - `/home/jj/.local/lib/python3.5/site-packages`
    - `/usr/local/lib/python3.5/dist-packages`
    - `/usr/lib/python3/dist-packages`
    - `_vim_path_`
 - jedi-vim git version: 37bd03c
 - jedi git submodule status:  02f238ce08f2d7f9c4af9a17cbf5754836775e2f pythonx/
jedi (v0.11.1)
 2ca629a2f6db2e905ddd5188113b1045f8a00fc2 pythonx/parso (v0.1.1)

  omnifunc=jedi#completions
        Last set from ~/.local/share/nvim/plugged/jedi-vim/autoload/jedi.vim
  completeopt=menuone,longest,preview
        Last set from ~/.local/share/nvim/plugged/jedi-vim/plugin/jedi.vim
```


#### :version
  completeopt=menuone,longest,preview
        Last set from ~/.local/share/nvim/plugged/jedi-vim/plugin/jedi.vim
```

#### :version
```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong
 -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG
-Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE
=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -peda
ntic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protecto
r-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
 -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-
0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/inc
lude -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src
/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages
```
"jiba.py" 9L, 123C
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong
 -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG
-Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE
=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -peda
ntic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protecto
r-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
 -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-
0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/inc
lude -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src
nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
```

<details><summary>:scriptnames</summary>

```
  1: ~/.config/nvim/init.vim
  2: ~/.local/share/nvim/site/autoload/plug.vim
  3: /usr/share/nvim/runtime/filetype.vim
  4: /usr/share/nvim/runtime/ftplugin.vim
  5: /usr/share/nvim/runtime/indent.vim
  6: /usr/share/nvim/runtime/syntax/syntax.vim
  7: /usr/share/nvim/runtime/syntax/synload.vim
  8: /usr/share/nvim/runtime/syntax/syncolor.vim
  9: ~/.local/share/nvim/plugged/jedi-vim/plugin/jedi.vim
 10: /usr/share/nvim/runtime/plugin/gui_shim.vim
 11: /usr/share/nvim/runtime/plugin/gzip.vim
 12: /usr/share/nvim/runtime/plugin/health.vim
 13: /usr/share/nvim/runtime/plugin/man.vim
 14: /usr/share/nvim/runtime/plugin/matchit.vim
 15: /usr/share/nvim/runtime/plugin/matchparen.vim
 16: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 17: /usr/share/nvim/runtime/plugin/rplugin.vim
 18: /usr/share/nvim/runtime/plugin/rrhelper.vim
 19: /usr/share/nvim/runtime/plugin/shada.vim
 20: /usr/share/nvim/runtime/plugin/spellfile.vim
 21: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 22: /usr/share/nvim/runtime/plugin/tohtml.vim
 23: /usr/share/nvim/runtime/plugin/tutor.vim
 24: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 25: ~/.local/share/nvim/plugged/jedi-vim/ftplugin/python/jedi.vim
 26: ~/.local/share/nvim/plugged/jedi-vim/autoload/jedi.vim
 27: /usr/share/nvim/runtime/autoload/provider/python3.vim
 28: /usr/share/nvim/runtime/autoload/provider/pythonx.vim
 29: /usr/share/nvim/runtime/autoload/remote/host.vim
 30: /usr/share/nvim/runtime/autoload/provider.vim
 31: /usr/share/nvim/runtime/ftplugin/python.vim
 32: ~/.local/share/nvim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 33: /usr/share/nvim/runtime/indent/python.vim
 34: /usr/share/nvim/runtime/syntax/python.vim
 35: ~/.local/share/nvim/plugged/jedi-vim/after/syntax/python.vim
```
</details>

### LINKED ISSUE #1012: Feature request : external commands
Hi !

Vim has tons of possible keybindings depending on the plugins installed and it can get really quickly messy
I'm not really confortable using keybindings to do really specific actions like refactoring
So, I've been wondering if it could be possible to enable the use of commands instead, like being able to type something like :JediRefactor or :JediGotoDef

Thanks for your work !

### LINKED ISSUE #1069: Vim hangs when working on files with fastai import
When I work on Python files that contain imports from the fast.ai library vim freezes for a long time. This only happens when the jedi-vim plugin is enabled.

The issue was already discussed [here](https://github.com/davidhalter/jedi/issues/1721), [here](https://githubmemory.com/repo/pappasam/jedi-language-server/issues/57) and [here](https://www.reddit.com/r/neovim/comments/lqtak6/how_to_set_a_coc_setting_for_jedi_language_server/).
The solution apparently is to add `"jedi.jediSettings.autoImportModules": ["fastai", "fastcore"],` to the coc config. Running `:CocConfig` doesn't work for me and it's unclear to me where I have to put the Lua code that was posted. 

Is there any code/config-option that I can paste directly into my vimrc?

### LINKED ISSUE #1090: <Ctrl-Space> doesn't work as expected at all
### Issue

`<Ctrl-Space>` doesn't work as expected at all. I've tried it in insert mode and in normal mode.

Vim version:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30)
Included patches: 1-3995
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-8W0Acv/vim-8.2.3995=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lm -ltinfo -lselinux -lsodium -lacl -lattr -lgpm -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -lpython3.10 -lcrypt -ldl -lm -lm
```

### Steps to reproduce

- Install `vim-plug`:
  ```
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  ```
- Change `~/.vimrc` to this one:
   ```vim
   :set number relativenumber
   call plug#begin()
   Plug 'davidhalter/jedi'
   call plug#end()
   ```
- Restart vim
- Run `:PlugInstall`
- Restart vim
- Open any python file (with .py extension)
- Enter insert mode and type `print(`
- Press <Ctrl-Space> and obtain `E29: No inserted text yet`

### PR DESCRIPTION
**Pull request by blueyed**
* pythonx/jedi 60415033...35e5cf2c (106):
      > A small Changelog improvement
      > Cleanup Changelog for the next release
      > Make it possible to access functions that were inherited, see #1347
      > Messed up a Windows test
      > Again a small windows issue fixed.
      > Need to escape the path backslash for windows slashes
      > Make it possible to access properties again
      > A small compatibility fix
      > Fix an issue with type vars that might have been a problem for other things as well
      > Don't add quotes after paths if they are already there
      > A small speed optimization that helps a lot with sys.version_info >= (3, 0) patterns in typeshed
      > Remove an unnecessary isinstance usage
      > Make CompiledValue lazy
      > A python 2 fix
      > Fix an error that occured because of some refactorings
      > Fix one more os.path.join issue
      > Fix more issues with os.path path completion
      > Make join detection much easier
      > Fix some remaining issues with file path completions
      > A few more tests for path completions (join)
      > Fix quote completions for os.path.join path completions
      > Fix first param argument of os.path.join file completions
      > Fix arglist/trailer issues
      > in os.path.join completions, directories should not end in a slash
      > Make some file path completions in os.path.join work
      > Fix os.path.join static value gathering
      > os.path.sep should always have a clear value
      > Fix string name completion for stuff like dirname and abspath
      > Fix bytes issue with file path adding
      > Python 2 compatibility
      > Make __file__ return the correct value
      > Fix string additions when used in certain ways
      > Make string additions work for file path completion
      > Fix interpeter project path
      > Fix the REPL completer for file path completions
      > Fix a few more file name completion cases
      > A first iteration for file path completions
      > Fix a test failure
      > Add Definition.execute, fixes #1076
      > Add tests to show that #516 is not working, yet
      > List possible Definition.type in its docstring, fixes #1069.
      > Start writing the Changelog for 0.15.0
      > 3.8-dev should not be allowed to fail
      > Skip more Python 2 tests
      > Skipping of tests was done the wrong way again
      > Skip the right tests
      > Parameter.kind is not avaialble in Python 3.5
      > Fix Python 2 test issues
      > Add a few docstrings to make some things clearer
      > Add ParamDefinition.kind, fixes #1361
      > Make it possible to format a param to a string, fixes #1074
      > Add another test for signature annotations
      > Add Signature.to_string() with proper tests, fixes #779, fixes #780
      > Test infer_default
      > Use a helper to create definitions
      > Add a execute_annotation option to infer_annotation
      > Test infer_annotation
      > Make it possible for users to infer annotations/defaults
      > A first iteration of adding signatures to the API, fixes #1139
      > Fix a caching issue
      > Forgot the right resolve_stars parameters in one place
      > Cache getting resolved param names
      > Turn around resolve_stars, it shouldn't by default be resolved
      > Remove a class that is not needed anymore
      > Revert "Use __str__ instead of to_string"
      > Fix the last remaining issues with function signature
      > overloaded_functions should be private
      > Use __str__ instead of to_string
      > Better repr for CallSignature
      > Fix some minor signature issues
      > Remove the unused function signature_matches
      > Fix signatures for __init__ calls when used with supers, fixes #1163
      > Fix some issues for args resolving in method calls
      > Remove a bit of code that i sprobably unused
      > Move get_signatures from Function to FunctionMixin
      > Merge the signature changes
      > Remove an import
      > Small refactoring
      > Skipped Python 2 Interpreter tests the wrong way
      > Remove a paragraph in docs that was arguing that stubs and generics (and other things) were not properly supported, fixes #1012
      > Fix partial signatures for MixedObject
      > Fix partial signatures, fixes #1371
      > Make sure with a test that the staticmethod signature is also correct
      > Fix classmethod signature, fixes #498
      > Deal with annotation on *args and **kwargs correctly, fixes #980
      > Use LazyContextWrapper more
      > Very small refactoring
      > Fix for failing assertion on native modules Issue #1354 (#1370)
      > Skip numpydoc tests for Python 2
      > Remove code that didn't mean anything
      > Fix docstrings for wrapped functions, fixes #906
      > Fix an isue about dict ordering in Python before 3.6.
      > Make it clearer when get_param is used.
      > A small dataclass refactoring
      > Evaluate annotations for dataclasses when infer is called on param
      > Get inheritance of dataclass right
      > A first working iteration of dataclass signatures, fixes #1213
      > Remove an unused function
      > Dataclass progress
      > Add enum changes to changelog
      > Fix a recursion error about getting metaclasses
      > One test about recursion issues only applied to Python 2
      > Use class filters in instances differently so metaclass plugins work, fixes #1090
      > First step in working with metaclasses in plugins, see #1090.
      > Refactor the plugin registry
      > Remove classes from plugins and use decorators instead

### CODE REVIEW

**Comment by davidhalter** [comment]
Thanks!

**Comment by blueyed** [comment]
You're welcome!
But why not wait for CI? :)

**Comment by blueyed** [comment]
Test failure bisected to https://github.com/davidhalter/jedi/commit/0352c3250ae9ad69dd1de78c37fc29895f3121ed.

**Comment by davidhalter** [comment]
Just realized that as well. Will fix it.

**Comment by davidhalter** [comment]
Forgot the CI :) Sorry!

**Pull request merged**
