### PR TITLE
Reset python init status when autoload/jedi.vim is resourced

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by davidhalter** [comment]
Why would we want that? Doesn't that bring more problems than it solves?

**Comment by blueyed** [comment]
@davidhalter 
I found it useful while improving the `JediDebugInfo` and think that it is good practice in general.
I think all entrypoints should be covered by a call to the `jedi#init_python` method.

Usually you do not re-source a file (and you need to unlet the `loaded` guards, which vim-scriptease is unseful for), but then it's good to reset it's state after all.

**Comment by davidhalter** [comment]
You're the expert ;)

**Comment by davidhalter** [comment]
BTW It looks horrible how much we have to do to initialize Python. :cry: :disappointed:

**Pull request merged**
