### PR TITLE
Report coverage

### PR DESCRIPTION
**Pull request by blueyed**
TODO:

- [x] requires #864 
- [x] rename flags to py27/py36

Includes/rebased on #864 for now.

### CODE REVIEW

**Comment by blueyed** [comment]
For some reason py2 is not working: https://travis-ci.org/davidhalter/jedi-vim/jobs/409612945

`:checkhealth` reports it to be ok, but during tests `has('python')` appears to be false.

**Comment by blueyed** [comment]
Found it:

> provider/pythonx: Could not load Python 2:^@          /home/travis/virtualenv/python2.7.14/bin/python2 is Python Coverage.py warning: --include is ignored because --source is set (include-ignored)^@          2.7 and cannot provide Python 2.

A Coverage.py warning apparently causes pytest to not detect py2 correctly.. :/

**Comment by blueyed** [comment]
20.9% coverage.. \o/

Needs some cleanup, but should be good then already (let's get the branches/PRs it depends on though in anyway).

Next step would be covimerage to track coverage for the Vimscript part.

**Comment by blueyed** [comment]
Should be good, but I want to cleanup/review it myself once more.

**Comment by blueyed** [comment]
I like it! ;)

Should be squash-merged (I can do it).

**Comment by davidhalter** [comment]
I'll just put you in charge for this. :) I like that we have coverage and don't really care how it's exactly done!

**Comment by blueyed** [comment]
Yeah! \o/

**Pull request merged**
